# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csuser/CPSC223/hw1-MAviles-Baquero

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csuser/CPSC223/hw1-MAviles-Baquero

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csuser/CPSC223/hw1-MAviles-Baquero/CMakeFiles /home/csuser/CPSC223/hw1-MAviles-Baquero/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csuser/CPSC223/hw1-MAviles-Baquero/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw1test

# Build rule for target.
hw1test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw1test
.PHONY : hw1test

# fast build rule for target.
hw1test/fast:
	$(MAKE) -f CMakeFiles/hw1test.dir/build.make CMakeFiles/hw1test.dir/build
.PHONY : hw1test/fast

#=============================================================================
# Target rules for targets named hw1perf

# Build rule for target.
hw1perf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw1perf
.PHONY : hw1perf

# fast build rule for target.
hw1perf/fast:
	$(MAKE) -f CMakeFiles/hw1perf.dir/build.make CMakeFiles/hw1perf.dir/build
.PHONY : hw1perf/fast

hw1_perf.o: hw1_perf.cpp.o

.PHONY : hw1_perf.o

# target to build an object file
hw1_perf.cpp.o:
	$(MAKE) -f CMakeFiles/hw1perf.dir/build.make CMakeFiles/hw1perf.dir/hw1_perf.cpp.o
.PHONY : hw1_perf.cpp.o

hw1_perf.i: hw1_perf.cpp.i

.PHONY : hw1_perf.i

# target to preprocess a source file
hw1_perf.cpp.i:
	$(MAKE) -f CMakeFiles/hw1perf.dir/build.make CMakeFiles/hw1perf.dir/hw1_perf.cpp.i
.PHONY : hw1_perf.cpp.i

hw1_perf.s: hw1_perf.cpp.s

.PHONY : hw1_perf.s

# target to generate assembly for a file
hw1_perf.cpp.s:
	$(MAKE) -f CMakeFiles/hw1perf.dir/build.make CMakeFiles/hw1perf.dir/hw1_perf.cpp.s
.PHONY : hw1_perf.cpp.s

hw1_test.o: hw1_test.cpp.o

.PHONY : hw1_test.o

# target to build an object file
hw1_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw1test.dir/build.make CMakeFiles/hw1test.dir/hw1_test.cpp.o
.PHONY : hw1_test.cpp.o

hw1_test.i: hw1_test.cpp.i

.PHONY : hw1_test.i

# target to preprocess a source file
hw1_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw1test.dir/build.make CMakeFiles/hw1test.dir/hw1_test.cpp.i
.PHONY : hw1_test.cpp.i

hw1_test.s: hw1_test.cpp.s

.PHONY : hw1_test.s

# target to generate assembly for a file
hw1_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw1test.dir/build.make CMakeFiles/hw1test.dir/hw1_test.cpp.s
.PHONY : hw1_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hw1test"
	@echo "... hw1perf"
	@echo "... hw1_perf.o"
	@echo "... hw1_perf.i"
	@echo "... hw1_perf.s"
	@echo "... hw1_test.o"
	@echo "... hw1_test.i"
	@echo "... hw1_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

